services:

  mongodb:
    image: mongo:4.2.15
    command: --wiredTigerCacheSizeGB 1 # 50% of (max RAM - 1GB) - minimum 0.25 (Modify it depending on defined RAM limits)
    deploy:
      resources:
        limits:
          memory: 3G # Maximum memory to allocate (Modify it depending on host ressources - leave at least 1GB free for host)
        reservations:
          memory: 1G # Minimum memory required
    restart: always
    environment:
      - MONGO_DB=pwndoc
    networks:
      - sso-network

  pwndoc-backend:
    build:
       context: ./backend
       dockerfile: Dockerfile
    environment:
      - DB_SERVER=mongodb
      - DB_NAME=pwndoc
      - LT_URL=http://pwndoc-languagetools:8010
      - LT_API_URL=http://pwndoc-languagetools:8020
    depends_on:
      - mongodb
    restart: always
    networks:
      - sso-network
    ports:
      - "4242:4242"

  pwndoc-languagetools:
    image: pwndoc/languagetools:prod
    build:
      context: ./languagetool/
      dockerfile: Dockerfile
    restart: always
    environment:
      - BACKEND_URL=https://pwndoc-backend:4242
    depends_on:
      - pwndoc-backend
    volumes:
      - ./languagetool/custom-rules:/LanguageTool/custom-rules
    networks:
      - sso-network

  pwndoc-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - pwndoc-backend
    networks:
      - sso-network
    ports: 
      - "8443:8443"

networks:
  backend:
    driver: bridge
  sso-network:
    external: true
    name: sso-network
